// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtmACpdp5WRYiRo81ZTUQeAslNc6R3pPk',
    appId: '1:319601638665:web:3cdeb0f0aedd58a179e7d8',
    messagingSenderId: '319601638665',
    projectId: 'siterh-ad136',
    authDomain: 'siterh-ad136.firebaseapp.com',
    storageBucket: 'siterh-ad136.appspot.com',
    measurementId: 'G-9590PMJBLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu2UOBh1tvwvItBBXPkGlR-VP189yKQcM',
    appId: '1:319601638665:android:4843ce4f8f9434b879e7d8',
    messagingSenderId: '319601638665',
    projectId: 'siterh-ad136',
    storageBucket: 'siterh-ad136.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5KruN2B5UWXCT_yfDymWIEklGYx4UOXQ',
    appId: '1:319601638665:ios:0fec4c72bcf7bfef79e7d8',
    messagingSenderId: '319601638665',
    projectId: 'siterh-ad136',
    storageBucket: 'siterh-ad136.appspot.com',
    iosBundleId: 'com.example.olaMundo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5KruN2B5UWXCT_yfDymWIEklGYx4UOXQ',
    appId: '1:319601638665:ios:89ac05692ad50e1d79e7d8',
    messagingSenderId: '319601638665',
    projectId: 'siterh-ad136',
    storageBucket: 'siterh-ad136.appspot.com',
    iosBundleId: 'com.example.olaMundo.RunnerTests',
  );
}
